program: modules/run_trial.py
name: 'v18'
project: 'Corejur'
method: bayes
metric:
  name: overall_f1
  goal: maximize
parameters:
  learning_rate:  
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-4
  model_name_or_path:
    values: ["xlm-roberta-base", "adalbertojunior/distilbert-portuguese-cased", "microsoft/deberta-v3-small"]
  per_device_train_batch_size: 
    values: [4, 8, 16]
  lr_scheduler_type: 
    values: ["linear", 'cosine_with_restarts', 'constant_with_warmup', 'polynomial']


early_terminate:
  type: hyperband
  min_iter: 5000