python src/model/run_ner_transformers.py \
  --task_name ner \
  --per_device_train_batch_size 8 \
  --learning_rate 2e-5 \
  --output_dir runs/v23_50_c \
  --seed 2 \
  --num_train_epochs 4 \
  --model_name_or_path pbert \
  --train_file data/posprocessed/v23_50/fold-0/train.json  \
  --validation_file data/posprocessed/v23_50/fold-0/dev.json \
  --test_file data/posprocessed/v23_50/test.json \
  --do_train \
  --do_eval \
  --do_predict \
  --report_to wandb \
  --max_seq_length 512 \
  --return_entity_level_metrics True \
  --save_total_limit 1 \
  --lr_scheduler_type linear \
  --gradient_accumulation_steps 1 \
  --gradient_checkpointing False \
  --fp16 True \
  --fp16_full_eval True \
  --metric_for_best_model eval_overall_f1 \
  --save_strategy steps \
  --evaluation_strategy steps \
  --eval_steps  1100 \
  --save_steps  1100 \
  --load_best_model_at_end True 